// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgC-EXo6zQtxOWswX7OefAai5_yAz1Iq0',
    appId: '1:325843575673:web:f49d3ebfd15c903ddbc5a8',
    messagingSenderId: '325843575673',
    projectId: 'permie-marocain',
    authDomain: 'permie-marocain.firebaseapp.com',
    storageBucket: 'permie-marocain.appspot.com',
    measurementId: 'G-FF11RNFQLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmXLfe0p7DdtRrmIf_kk47kq6DuzF-CE',
    appId: '1:325843575673:android:d29760f0b4cf74b7dbc5a8',
    messagingSenderId: '325843575673',
    projectId: 'permie-marocain',
    storageBucket: 'permie-marocain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBO1QEVoHuGVBNvFUjIH-iNpjS6i_WoUI',
    appId: '1:325843575673:ios:34e7433d50ca411edbc5a8',
    messagingSenderId: '325843575673',
    projectId: 'permie-marocain',
    storageBucket: 'permie-marocain.appspot.com',
    iosBundleId: 'com.example.permisMarocain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBO1QEVoHuGVBNvFUjIH-iNpjS6i_WoUI',
    appId: '1:325843575673:ios:34e7433d50ca411edbc5a8',
    messagingSenderId: '325843575673',
    projectId: 'permie-marocain',
    storageBucket: 'permie-marocain.appspot.com',
    iosBundleId: 'com.example.permisMarocain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgC-EXo6zQtxOWswX7OefAai5_yAz1Iq0',
    appId: '1:325843575673:web:2e7283bc6a95fcd4dbc5a8',
    messagingSenderId: '325843575673',
    projectId: 'permie-marocain',
    authDomain: 'permie-marocain.firebaseapp.com',
    storageBucket: 'permie-marocain.appspot.com',
    measurementId: 'G-HCQV2QR102',
  );
}
